require('dotenv').config();
const { Client } = require('pg');

async function setup() {
    const client = new Client({
        connectionString: "postgres://postgres.epdjybbgfpegrijisjqw:UyF4Te3mIBWW8HfF@aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres",
        ssl: { rejectUnauthorized: false }
    });

    try {
        await client.connect();
        console.log('Connected to DB');

        // Create chat_messages table
        await client.query(`
            CREATE TABLE IF NOT EXISTS chat_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
                email TEXT,
                message TEXT NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
            );
        `);
        console.log('Table chat_messages created or verified');

        // Allow unauthenticated/authenticated reads (for realtime) and inserts
        // Since we are doing a quick community chat, we'll just allow authenticated users
        await client.query(`
            ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
            
            -- Policy for selecting messages
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies WHERE tablename = 'chat_messages' AND policyname = 'Enable read access for all users'
                ) THEN
                    CREATE POLICY "Enable read access for all users" ON chat_messages FOR SELECT USING (true);
                END IF;
            END
            $$;
            
            -- Policy for inserting messages
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_policies WHERE tablename = 'chat_messages' AND policyname = 'Enable insert for authenticated users only'
                ) THEN
                    CREATE POLICY "Enable insert for authenticated users only" ON chat_messages FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
                END IF;
            END
            $$;
        `);
        console.log('RLS policies enabled');

        // Enable realtime for chat_messages
        await client.query(`
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'chat_messages'
                ) THEN
                    ALTER PUBLICATION supabase_realtime ADD TABLE chat_messages;
                END IF;
            END
            $$;
        `);
        console.log('Realtime enabled for chat_messages');

    } catch (e) {
        console.error('Error:', e);
    } finally {
        await client.end();
    }
}

setup();
